version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
  backend:
    build: ./flask/
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ".\\compose\\6-bind-mount-compose\\flask:/app"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  dockercompose:
